// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt824qUoS6XF8E_mX8-FyN0cljPjhcvZY',
    appId: '1:200208340750:web:5ea59c066256c8c354295f',
    messagingSenderId: '200208340750',
    projectId: 'finance-app-4bb4f',
    authDomain: 'finance-app-4bb4f.firebaseapp.com',
    storageBucket: 'finance-app-4bb4f.firebasestorage.app',
    measurementId: 'G-YJRKRVG0ZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5yvHH59bk9lv0WA7wvMJiX_ns6vdxPqQ',
    appId: '1:200208340750:android:b5d3d2c00d03370554295f',
    messagingSenderId: '200208340750',
    projectId: 'finance-app-4bb4f',
    storageBucket: 'finance-app-4bb4f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI09ZOQE66Yq1hY2rAxa8BJ5LWgFZ7M4A',
    appId: '1:200208340750:ios:db887c024cffd96c54295f',
    messagingSenderId: '200208340750',
    projectId: 'finance-app-4bb4f',
    storageBucket: 'finance-app-4bb4f.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDI09ZOQE66Yq1hY2rAxa8BJ5LWgFZ7M4A',
    appId: '1:200208340750:ios:db887c024cffd96c54295f',
    messagingSenderId: '200208340750',
    projectId: 'finance-app-4bb4f',
    storageBucket: 'finance-app-4bb4f.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBt824qUoS6XF8E_mX8-FyN0cljPjhcvZY',
    appId: '1:200208340750:web:9db3c9d85fd03e6354295f',
    messagingSenderId: '200208340750',
    projectId: 'finance-app-4bb4f',
    authDomain: 'finance-app-4bb4f.firebaseapp.com',
    storageBucket: 'finance-app-4bb4f.firebasestorage.app',
    measurementId: 'G-LBNQ45G8R4',
  );
}
